spring:
  profiles:
    active: dev
  datasource:
      url: jdbc:mysql://localhost:3306/demo?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: wangyongzhi610
      driver-class-name : com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true